### ISSUE TITLE
 Could not determine how to assign __set on CLASS

### ISSUE THREAD

**Issue by tristanbes** [nelmio/alice#158] opened 2014-11-12 14:37 UTC
Hi,

I'm using the latest version of this bundle, and in a fixture file, i want to call a custom setter (`setExtensions`) on my Object called `Site`

The problem is that it throws me an error : 
```
[UnexpectedValueException]                                            
  Could not determine how to assign __set to a Site object
```

My fixture looks like : 
```yml
Site:
    site_1:
        __set: setExtensions
        extensions: [extension_team, extension_article, extension_site_navigation, extension_contact_form, extension_image_slider, extension_location, extension_newsletter, extension_ylly_services, extension_reminder]
```

Do you have an idea on what can cause this please ?

**Comment by theofidry** [comment] 2016-05-04 22:40
Closing this issue as it's fairly old and there is tests for it. If the issue is still relevant please feel free to express yourself or open a new issue.

**Closed by theofidry** 2016-05-04 22:40 UTC
