### ISSUE TITLE
html code in fields

### ISSUE THREAD

**Issue by malutanpetronel** [nelmio/alice#1063] opened 2020-12-05 14:40 UTC
I was using from 2012 HTML code in text fields like bellow 
...
    modul3:
        title: 'POEZIE'
        text: >
                <p>Scrierea unei poezii frumoase este un proces de continua imaginatie, revizuire a rimelor si de echilibrare a versurilor.</p>
                <p>Scrie si noi te facem cunoscut.</p>

in a symfony 2.8 which now I've upgraded to 4.3
and see is no longer accepting html code from text fields ?

**Comment by theofidry** [comment] 2021-02-23 21:03
Closing as a duplicate of https://github.com/nelmio/alice/issues/840; I do not think this is due to a Symfony difference but it certainly changed between 2.x & 3.x

**Closed by theofidry** 2021-02-23 21:03 UTC
