### ISSUE TITLE
object property undefined after referencing it

### ISSUE THREAD

**Issue by kermorgant** [nelmio/alice#841] opened 2017-12-13 13:56 UTC
Hi,

I'm using hautelook/alice to load fixtures in my project. 

I got an issue on a particular one named "Instance" that takes a "InstanceOrder" as constructor argument.

```
    public static function constructFromOrder(InstanceOrder $instanceOrder)
    {
        // ...
        $instance->smtpConfiguration = $instanceOrder->getSmtpConfiguration();
        return $instance;
    }

```

Everything was working fine until I added this 

```
AppBundle\Entity\SubscriptionItem:
    sub1_item1:
        subscription: '@customer1_sub1'
        __construct: ['@plan2_v1', '@instance_order2->getUid()']
```

With that, the $instanceOrder's smtpConfiguration property is null instead of being set as it should.

And I get 

`  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'smtp_configuration_id' cannot be null   
`

Here.s the details of the packages in use https://gist.github.com/kermorgant/c247b4af4718b15fd89080f528efb956

**Comment by theofidry** [comment] 2017-12-17 13:54
Hi,

I don't think I can help without more information... What you're doing is the equivalent of doing in raw PHP:

```php
$subscription = new SubscriptionItem($plan2_v1, $instanceOrder2->getUid());
$subscription->setSubscription($customer1_sub1);
```

There is not much more magic than that, but without more complete code samples and config I really can't guess what the issue is.

**Comment by kermorgant** [comment] 2017-12-18 07:45
I understand. Unfortunately, I did not have enough available time to setup a repo for that but I hope it will be possible in january.

**Comment by theofidry** [comment] 2018-02-19 22:16
Closing as I can't help with that for now :( Please feel free to open a new issue when you have more information about it :)

**Closed by theofidry** 2018-02-19 22:16 UTC
Labels: Unconfirmed
