### ISSUE TITLE
Not seen in the DOCS.

### ISSUE THREAD

**Issue by malutanpetronel** [nelmio/alice#1105] opened 2022-02-04 16:50 UTC
HTML still not working as input as described bellow ?

Using > in yaml is trivial and working from ancient times. I am still wondering how to input this text into DB or what tricks should be done for make it work as both versions bellow are not able to be used. 

Is it any reason is not shown in the documentation ?

    some1:
        title: creation
        author: gogu
        blog: >
            we handle article
            <ul>
                <li>123</li>
            </ul>

            
    some2:
        title: creation
        author: gogu
        blog: >
            <identity('
            we handle article
            <ul>
                <li>123</li>
            </ul>
            ')>            

With kind regards

**Comment by malutanpetronel** [comment] 2022-02-04 17:13
parameters:
    text1:
        <ul\>
        <li>123</li\>
        </ul>
        
    some3:
        title: creation
        author: Petro
        blog: >
            <identity('
            Some titel
            <{text1}>
            ')>
            
I get 

In main.php line 50:
                                                                                                
  Warning: DOMDocument::loadHTML(): htmlParseStartTag: invalid element name in Entity, line: 1

**Comment by malutanpetronel** [comment] 2022-02-04 17:13
bin/console doctrine:fixtures:load --em=blog --env=www --group=www

**Comment by malutanpetronel** [comment] 2022-02-04 17:47
BIG SECRET :) use <{html}> which you can define in parameters:
Thank you

**Comment by malutanpetronel** [comment] 2022-02-04 17:54
However organizing a file like:

parameters:
  page1_html1:
  page1_html2:

page1:
  title: Title1
  text: <{page1_html1}>
page2:
  title: Title1
  text: <{page2_html1}>
  
seems horrible imo. I use for example in a yaml file 2030 lines. Now need to extract each html code into another tag... For my case this was not a big improvement... Also changing 

<randomElement($array = array ('el1, el2, el3, el4'))>
to 
<randomElement(['el1, el2, el3, el4'])>
but... is how life goes on and we keep having works to do...

**Comment by theofidry** [comment] 2022-02-07 14:58
I highly suggest to rely on a [custom faker provider](https://github.com/nelmio/alice/blob/master/doc/customizing-data-generation.md#custom-faker-data-providers) which I think removes the need to escape the whole thing

**Comment by theofidry** [comment] 2022-02-12 10:53
I'll close this as a duplicate of #840

**Closed by theofidry** 2022-02-12 10:53 UTC
