### ISSUE TITLE
How to call a setter after the construct 

### ISSUE THREAD

**Issue by petegore** [nelmio/alice#293] opened 2015-11-24 17:57 UTC
Hey,

I want to create an entity using the __construct() method. 
But then, I immediately want to set another attribute of this entity, but using a setter (because I don't want the constructor to support that attribute creation).
I tried that but, of course, it does not work : 

```yaml
person1:
    __construct:
        - <username()>
        - <password()>
        - etc...
    setPostalAddress(@postalAddress*)
```

Any idea to do that ?

**Comment by fabiocarneiro** [comment] 2015-12-04 18:30
+1 on this

For me its because this attribute is NEVER created when the object is created, but it is part of its behavior.

**Comment by theofidry** [comment] 2016-06-06 08:51
Closing as is a duplicate of #313

**Closed by theofidry** 2016-06-06 08:51 UTC
Labels: Feature
