### ISSUE TITLE
Passing in the previous exception does not display the previous message

### ISSUE THREAD

**Issue by jeremy-smith-maco** [nelmio/alice#769] opened 2017-07-10 23:36 UTC
Exception displays `Could not resolve value during the generation process` and nothing else helpful to the user even though `$previous` is passed into the exception.

**Comment by theofidry** [comment] 2017-08-01 22:58
I'm not sure what should be done here. Maybe take a look at the verbosity when running your command.

If it's directly in the code, it's at PHP level. Maybe there's a setting for it otherwise the way to go is do step by step debugging and inspect the exception

**Comment by jeremy-smith-maco** [comment] 2017-08-01 23:01
I was just running a standard PHPUnit test suite. Ended up having to do step by step debugging but it should display a move helpful exception message rather than having to debug each time that message occurs.

**Comment by theofidry** [comment] 2017-08-01 23:03
The problem is that resolving a value can be far from trivial and having just the previous error message is very rarely enough, so in any case you need the whole stack trace. The question is if it can be displayed easily or not, but I'm not sure this is something that can be done at alice level

**Comment by jeremy-smith-maco** [comment] 2017-08-01 23:06
Yeah, it just doesn't display anything helpful in the message. The stack trace is helpful but a better error message saying exactly what's wrong would be nice but if it's not possible then oh well.

**Comment by theofidry** [comment] 2017-08-01 23:08
Well that's the issue, it's hard to tell :)

It's an error that shouldn't happen and is very contextual, so rather than trying to be fancy and completely wrong, I've opted for a generic error message with the proper stack trace.

I understand it can be a bit frustrating, but in my experience at least it's very hard to have an error message that is somewhat helpful here

**Comment by jeremy-smith-maco** [comment] 2017-08-01 23:11
When I was upgrading 2.x to 3.x I was just using the `$previous` variable as the exception message which seemed to prove pretty helpful in my case as I didn't have to debug each time.

**Comment by theofidry** [comment] 2017-08-01 23:14
If you want to you could append the error message of the previous version to it, it's just that I never found it enough :P

**Comment by jeremy-smith-maco** [comment] 2017-08-01 23:17
I guess it's just a case-by-case sort of thing lol.

**Comment by theofidry** [comment] 2017-09-12 22:08
Closing for now as I really don't have a good solution for it and not really willing to spend too much time on it. If someone has a good idea he can give it a stab though :)

**Closed by theofidry** 2017-09-12 22:08 UTC
