### ISSUE TITLE
Entity of type [..] is missing an assigned ID for field 'id'

### ISSUE THREAD

**Issue by vitalyiegorov** [nelmio/alice#954] opened 2018-09-19 09:11 UTC
@everzet I have found strange behavior, issue itself and my investigation is described here hautelook/AliceBundle#413 

In general problem is related to id generation within entity relations and their persisting.

**Comment by theofidry** [comment] 2018-09-19 10:37
Hi,

Since I'm the maintainer on both package I would rather have only one issue. Also since nelmio/alice 3.x has no concept of persistence whatsoever I highly doubt the issue is there :)

So I'll be closing this one, let's keep it going in hautelook/AliceBundle#413 and a new issue can be open in the appropriate repository once we found out what the problem is

**Closed by theofidry** 2018-09-19 10:37 UTC
