### ISSUE TITLE
Optional method call

### ISSUE THREAD

**Issue by appeltaert** [nelmio/alice#249] opened 2015-09-01 14:28 UTC
Hi, 

Is the [optional data](https://github.com/nelmio/alice/blob/master/doc/complete-reference.md#optional-data) syntax possible for setters? Something like:

```yaml
Nelmio\Entity\User:
    user1:
        username: <username()>
        setLocation: 50% [40.689269, -74.044737]
```

The reason im asking is because this example as shown in the docs is a perfect example, if you were to have User entities with a location or not, where location is 2 separate fields of long/latitude--then i want either both or none of them set.

Another example is companies where some have poboxes or not, and again where you want all of the pobox fields filled in or none of them.

I can think of some hacky solution though a [custom setter](https://github.com/nelmio/alice/blob/master/doc/complete-reference.md#custom-setter), but using the ternary operator for method calls would be awesome.

**Comment by appeltaert** [comment] 2015-09-01 15:03
Being able to conditionally/variably inherit another [fixture](https://github.com/nelmio/alice/blob/master/doc/fixtures-refactoring.md#fixture-inheritance) would be a good solution also.

**Comment by appeltaert** [comment] 2015-09-01 15:08
Not possible using [variables](https://github.com/nelmio/alice/blob/master/doc/fixtures-refactoring.md#variables) either.

```php
postalZipcode: 50%? <nl_NL:postcode()>
postalNo: $postalZipcode? <nl_NL:buildingNumber()>
```

**Comment by appeltaert** [comment] 2015-09-01 15:25
Man, silly..
 
```php
company_pobox (template):
    postalZipcode: <nl_NL:postcode()>
    postalNo: <nl_NL:buildingNumber()>
    postalCity: <nl_NL:city()>
company{1..10} (extends company_pobox):
```

**Comment by Seldaek** [comment] 2015-09-02 11:08
I think `setLocation: 50%? [foo, bar]` should be supported, this seems like a reasonable expectation. Let's leave this open :)

**Comment by jguittard** [comment] 2016-05-04 15:27
+1

**Comment by theofidry** [comment] 2016-09-04 22:58
Closing this one as a duplicate of #388

**Closed by theofidry** 2016-09-04 22:58 UTC
Labels: Feature
