### ISSUE TITLE
Having same template names but different classes

### ISSUE THREAD

**Issue by jeremy-smith-maco** [nelmio/alice#765] opened 2017-07-05 04:54 UTC
Currently we have two class names that are the same in different namespaces and we are using the same template names for each one in our base fixture files which many many other fixtures extend from. We could do it in 2.x with no problems but with 3.x it tries to assign properties of one of the class objects to the other one and then throws an exception for it even though they are different classes entirely. It only happens with fixtures files using two fixtures that extend from both templates. Our files would look something like this:

```yaml
# Example\One\Id.yml
Example\One\Id:
    SomeId (template):
       oneValue: 2
```

```yaml
# Example\Two\Id.yml
Example\Two\Id:
    SomeId (template):
        twoValue: 1
```

```yaml
# Test\Example\Three\Test.yml
Example\One\Id:
    OneTestId (extends SomeId): {}

Example\Two\Id:
    TwoTestId (extends SomeId): {}
```

So in Alice 2.x that is a valid fixture setup but in 3.x it causes issues. The stack trace for something like the above example would look like this:

```
Could not hydrate the property "twoValue" of the object "OneTestId" (class: Example\One\Id).
 /vendor/nelmio/alice/src/Throwable/Exception/Generator/Hydrator/HydrationExceptionFactory.php:85
 /vendor/nelmio/alice/src/Generator/Hydrator/Property/SymfonyPropertyAccessorHydrator.php:61
 /vendor/nelmio/alice/src/Generator/Hydrator/SimpleHydrator.php:89
 /vendor/nelmio/alice/src/Generator/ObjectGenerator/SimpleObjectGenerator.php:103
 /vendor/nelmio/alice/src/Generator/ObjectGenerator/SimpleObjectGenerator.php:91
 /vendor/nelmio/alice/src/Generator/ObjectGenerator/CompleteObjectGenerator.php:53
 /vendor/nelmio/alice/src/Generator/DoublePassGenerator.php:60
 /vendor/nelmio/alice/src/Generator/DoublePassGenerator.php:51
 /vendor/nelmio/alice/src/Loader/SimpleDataLoader.php:49
 /vendor/nelmio/alice/src/Loader/SimpleFileLoader.php:49
 /vendor/nelmio/alice/src/Loader/NativeLoader.php:237
/** Root test file **/
```

Obviously a workaround is not having the same template names but you should be allowed to extend from two templates with the same name in the same fixture file if they are completely different classes.

**Comment by theofidry** [comment] 2017-07-05 07:48
How do you load those files exactly?

Also the issue seems to come from the fact that the property `twoValue` was not found in `Example\Two\Id`, not about the template names conflicting

**Comment by jeremy-smith-maco** [comment] 2017-07-05 08:15
They get loaded through `loadFile` method of the  `NativeLoader`. We have a helper class that has a `load` function which calls `loadFile` with the file name inclusive of directory along with any parameters to be injected. No parameters are getting injected in some of the files that are having this issue.

**Comment by theofidry** [comment] 2017-07-05 08:49
>Could not hydrate the property "twoValue" of the object "OneTestId" (class: Example\One\Id).

I think it's worth checking the error thrown (dump it, see the previous error) to see why the hydration fail

**Comment by theofidry** [comment] 2017-07-09 11:49
I can confirm this behaviour works in 2.x as https://github.com/nelmio/alice/pull/766 shows. However this is *pure luck*.

A fixture ID is its name, the class is not taken into consideration. The reason being that in the final array objects you get it's an associative array where the fixture ID is the key:

```yaml
Dummy:
  dummy: {}

AnotherDummy:
  dummy: {}
```

will result in:

```
[
  'dummy' => $dummy,
]
```

So one will be overridden for sure. You scenario simply just make it a bit less obvious as template fixtures never appear in the result anyway.

So it's a "won't fix" for 3.x. What could be done however is adding a deprecation message in 2.x for that behaviour.

**Closed** 2017-07-09 11:51 UTC
