### ISSUE TITLE
Problem with "(unique): <password()>"

### ISSUE THREAD

**Issue by GrzegorzW** [nelmio/alice#489] opened 2016-08-12 11:48 UTC
Hi,

I have problem with unique password values.

### After tests I get:

> 35) tests\AppBundle\Controller\Worker\DeviceControllerTest::testCreateDeviceAction
UnexpectedValueException: Instance vlLUDSd is not defined

> /vagrant/public/symfony/vendor/nelmio/alice/src/Nelmio/Alice/Instances/Collection.php:113
> /vagrant/public/symfony/vendor/nelmio/alice/src/Nelmio/Alice/Instances/Processor/Methods/Reference.php:87
> /vagrant/public/symfony/vendor/nelmio/alice/src/Nelmio/Alice/Instances/Processor/Processor.php:97
> /vagrant/public/symfony/vendor/nelmio/alice/src/Nelmio/Alice/Instances/Populator/Populator.php:124
> /vagrant/public/symfony/vendor/nelmio/alice/src/Nelmio/Alice/Instances/Populator/Populator.php:91
> /vagrant/public/symfony/vendor/nelmio/alice/src/Nelmio/Alice/Fixtures/Loader.php:309
> /vagrant/public/symfony/vendor/nelmio/alice/src/Nelmio/Alice/Fixtures/Loader.php:147
> /vagrant/public/symfony/vendor/nelmio/alice/src/Nelmio/Alice/Fixtures.php:141
> /vagrant/public/symfony/vendor/nelmio/alice/src/Nelmio/Alice/Fixtures.php:104
> /vagrant/public/symfony/vendor/liip/functional-test-bundle/Test/WebTestCase.php:561
> /vagrant/public/symfony/tests/ApiWebTestCase.php:60

#### $valueOrProcessable:
>`object(Nelmio\Alice\Fixtures\PropertyDefinition)#324511 (4) {
  ["name":"Nelmio\Alice\Fixtures\PropertyDefinition":private]=>
  string(7) "temp_pw"
  ["nameFlags":"Nelmio\Alice\Fixtures\PropertyDefinition":private]=>
  array(1) {
    ["unique"]=>
    bool(true)
  }
  ["value":protected]=>
  string(12) "<password()>"
  ["matches"]=>
  array(0) {
  }
}`

#### $value:
>`string(8) "@vlLUDSd"`

### My fixtures file:
AppBundle\Entity\Company:
    company_1:
        name:` <company()>`
        street: `<streetAddress()>`
        city: `<city()>`
        post_code: `<postcode()>`
        subdomain: `<domainWord()>`
        nip: `<numberBetween(1000000, 9000000)>`
        main_site: `<url()>`
        email_subject_begin: `<text(30)>`
        updatedAt: `<(new \DateTime('2015-01-01 15:00:00'))>`

AppBundle\Entity\Localization:
    localization (template):
        name: `<streetName()>`
        street: `<streetAddress()>`
        city: `<city()>`
        post_code: `<postcode()>`
        tel_1: `<(\libphonenumber\PhoneNumberUtil::getInstance()->parse('+48' . random_int(600000000, 699999999), 'PL'))>`
        tel_2: `<(\libphonenumber\PhoneNumberUtil::getInstance()->parse('+48' . random_int(600000000, 699999999), 'PL'))>`
        tel_3: `<(\libphonenumber\PhoneNumberUtil::getInstance()->parse('+48' . random_int(600000000, 699999999), 'PL'))>`
        email_first: `<email()>`
        email_second: `<email()>`
        mon_fri_open: `<email()>`
        sat_open: `<numberBetween(5, 10)>-<numberBetween(11, 20)>`
        sun_open: `<numberBetween(5, 9)>-<numberBetween(10, 15)>`

  company_1_localization_1 (extends localization):
    __construct: ['@company_1']

AppBundle\Entity\User:
    user_{1..100}:
        __construct: ['@company_1_localization_1']
        username (unique): `<userName()>`
        username_canonical (unique): `<userName()>`
        email (unique): `<email()>`
        email_canonical (unique): `<email()>`
        salt: dsev8aa5klk4gk04cwsko4oog0g8sk0
        password: $2y$13$dsev8aa5klk4gk04cwskouuxO5C5tVh.JzEG0TE1645kQgHMO1N1a
        enabled: 1
        expired: 0
        locked: 0
        credentials_expired: 0
        alt_id: `<numberBetween(1000, 9999)>`
        name: `<firstName()>`
        surname: `<lastName()>`
        tel: <(\libphonenumber\PhoneNumberUtil::getInstance()->parse('+48' . random_int(600000000, 699999999), 'PL'))>
        temp_pw (unique): `<numberBetween(10000, 99999)>`
        temp_pw_changed: 1
        marketing_agreement: 1
        first_login_modal_rendered: 1
        roles: [ROLE_USER]
    

The problem occurs only, when:
`temp_pw (unique): <password()>`
Does anyone know why it looks for object instance which name is password value?
Ps. `temp_pw (unique): <numberBetween(10000, 99999)>`  works perfectly every time.

**Comment by theofidry** [comment] 2016-08-18 10:46
Duplicate of https://github.com/nelmio/alice/issues/428. The issue is that the generated password has a `@` which will make alice think this will be a reference.

**Closed by theofidry** 2016-08-18 10:46 UTC
