### ISSUE TITLE
Optional Data Calls Provider Regardless of Persistence

### ISSUE THREAD

**Issue by ReservedDeveloper** [nelmio/alice#202] opened 2015-04-21 21:29 UTC
I've been utilizing the [Optional Data](https://github.com/nelmio/alice/tree/1.7.2#optional-data) feature of Alice in conjunction with the [Faker Image provider](https://github.com/fzaninotto/Faker/tree/v1.4.0#fakerproviderimage). During testing, I noticed a peculiarity. Namely, providers are called regardless of whether or not data is persisted. In a loop of 200 w/ a 5% persistence rate, I have 200 images in my directory, and 23/200 have images persisted on the DB side.

Not sure if this is a bug, or just an undocumented aspect of the Optional Data feature. My specific use case would lean toward bug, as I don't want data downloaded/generated that I'm going to use. Could anyone clarify expected behavior here?

**Comment by ReservedDeveloper** [comment] 2015-04-21 21:35
Two things of note:

  1. I was using the Faker provider via a custom provider. Shouldn't have any impact, but felt it worth mentioning.
  2. I see [here](https://github.com/nelmio/alice/blob/1.7.2/src/Nelmio/Alice/Loader/Base.php#L583-584) where the true value is being parsed. I'd be interested to know why the true value is always needed. It only appears to be used to confirm value type in the event of an empty/outside-of-threshold instance.

**Comment by ReservedDeveloper** [comment] 2015-04-21 21:48
@Seldaek After further digging, I see the lines I linked were part of the initial commit. Could you provide any additional context around the reason the true value is always needed? Why does the library need to return an empty array if type array?

Would it be at all possible to rework so that the caller handles returning an empty type (ex via `##% <trueCall()>: []` or similar)?

**Comment by Seldaek** [comment] 2015-05-10 16:31
I think this issue was just overlooked, I don't think it's by design. I agree if the optional data doesn't trigger then it shouldn't be generated. Not sure how easy that is to implement but if you wanna have a go at that in the master branch that sounds good.

About the `50%? true : false` thing, that'd be a new feature and it sounds a bit risky in case the generated `true` case contains a `:` or something. Given we don't have a proper lexer for this whole syntax mess we have to be careful :) I'd say defaulting your model to have the empty data sounds safer.

**Comment by theofidry** [comment] 2016-11-08 22:29
Regarding the issue of the optional data being triggered when it shouldn't be generated: this has been addressed in 3.x.

About the `50%? true : false`, this is doable although you need to use a function to cast the string value into a boolean. There is a discussion in #597 about integrating it in the core.

**Closed by theofidry** 2016-11-08 22:29 UTC
