### ISSUE TITLE
[Ternary operator] Conditional and referenced object 

### ISSUE THREAD

**Issue by k-przybyszewski** [nelmio/alice#324] opened 2016-04-07 08:31 UTC
Hi there,

The issue is when you are working with the YML file and ternary operator with reference object string the syntax:
`size: 50%? '@size*'` - is not working properly. As string is not converted into referenced object.

I did a bit of investigation and found a solution which works for me:
`size: 50%? @size*`

The problem is that "skip brackets while using conditions" is not mentioned in the documentation.

Best! 
Thanks

**Comment by theofidry** [comment] 2016-05-08 21:34
Closing as is a duplicate of #325, thanks for the report!

**Closed by theofidry** 2016-05-08 21:34 UTC
