### ISSUE TITLE
"INT x randomElement"  not working

### ISSUE THREAD

**Issue by digitalkaoz** [nelmio/alice#190] opened 2015-03-25 12:32 UTC
im trying to do the following, but it wont work:

```yml
\NumberValue:
  number_value{1..10}:
    #..

\StringValue:
  string_value{1..10}:
    #..

\EntityValue:
  entity_value{1..10}:
    #..

\MyObject:
  my_object{1..10}:
    values: 10x <randomElement([@number_value*, @number_value*, @entity_value*])>
```

it would be cool to support this, or is it even possible? or exists there a workaround?

it tried it with a custom `Provider` but i cant pass a whole fixture instance to it like:

```yml
\MyObject:
  my_object{1..10}:
    values: <randomValue([@number_value, @number_value, @entity_value], 10)>
```

**Comment by Seldaek** [comment] 2015-03-25 14:16
What do you by can't pass a whole fixture instance? If randomValue returns an array it should hopefully pass that on to the values property, but I am not sure if it'll try to stringify it or not..

**Comment by digitalkaoz** [comment] 2015-03-25 14:29
i would like to pass all objects of e.g. `@number_value` to a function.

but the first solution:

```yml
values: 10x <randomElement([@number_value*, @number_value*, @entity_value*])>
```

would be better i think

**Comment by Seldaek** [comment] 2015-03-31 17:24
Oh ok, I guess what you would need is rather grabbing the instances directly from the loader itself.

**Comment by kminh** [comment] 2015-06-09 14:13
Might be related, but is this possible:

```yaml
My\Entity:
    entity:
        languages: 3x <languageCode()>
```

Right now it appears as "3x en", "3x fr" in database.

**Comment by luispabon** [comment] 2015-11-26 12:18
Same problem as @kminh , I was expecting that to work.

**Comment by theofidry** [comment] 2016-05-04 23:01
Closing as duplicate of #191

**Closed by theofidry** 2016-05-04 23:01 UTC
Labels: Feature
